language: ruby
rvm:
  - 2.3.1

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  SECRET_KEY_BASE="$(bundle exec rake secret)"

script:
  - export RAILS_ENV=test
  - bundle exec rake db:migrate
  - bundle exec rspec spec --require spec_helper --require rails_helper