# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffddf06fdcd2eb1edab282a28dd841bbd8c259a6cfbf25a767d45f3fa71147f0974c52a5d6217b6d80c61076777a75bf8ca82094b68c06993c62fe44cb28f45b

test:
  secret_key_base: e9d39fea69727501267e31c384ce92973c0184c5fceb62af1ac5b10ce4a6f04107fe04a02d9d55f853b723e4d575dbb2ca4ec1b27523ff24a9682df8d821941c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
